### ISSUE TITLE
Please test myLogSeqBlog

### ISSUE THREAD

**Issue by scripting** [scripting/myLogseqBlog#1]
Follow the instructions in the readme, and report success or problems here. Thanks! :-)

https://github.com/scripting/myLogseqBlog/blob/main/README.md

**Comment by sabre23t** [comment]
Unfortunately I got stuck. 

I followed the steps in [myLogseqBlog README.md](https://github.com/scripting/myLogseqBlog#readme).
	(1) Downloaded `myLogseqBlog-main.zip`
	(2) Unzipped  it into a folder `.\Drummer\myLogseqBlog-main`
	(3) From that folder, tried to do `npm install` but not recognized by windows command line. I don't have NPM installed on my Windows. Downloaded/installed `https://nodejs.org/dist/v16.13.2/node-v16.13.2-x64.msi` from [nodejs.org](https://nodejs.org/en/). Then `npm install` installed *mylogseqblog v0.4.0*
	(4) Configure `config.json` with blog settings.
	(5) Use it by `node mylogseqblog.js` from that `.\Drummer\myLogseqBlog-main` but stopped at following error ...

```
d:>node mylogseqblog.js
readConfig: err.message == Unexpected token + in JSON at position 321
config == {
    "blogUseCache": false,
    "urlTwitterServer": "http://drummer.scripting.com/"
}
node:internal/fs/utils:670
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.readdir (node:fs:1356:10)
    at readJournalFolderIntoOutline (d:\Data\Dropbox\R&D\R&D-2020\Drummer\myLogseqBlog-main\mylogseqblog.js:243:5)
    at saveMyLogSeqOpml (d:\Data\Dropbox\R&D\R&D-2020\Drummer\myLogseqBlog-main\mylogseqblog.js:255:2)
    at d:\Data\Dropbox\R&D\R&D-2020\Drummer\myLogseqBlog-main\mylogseqblog.js:277:2
    at d:\Data\Dropbox\R&D\R&D-2020\Drummer\myLogseqBlog-main\mylogseqblog.js:47:3
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}

d:>
```

That seems to be unable to read the Logseq Journal Folder string. I've tried the following strings in `config.json`, all with similar error ...
```
"logSeqJournalFolder": "d:\Data\Dropbox\R&D\R&D-2020\KLTransitLogseq\journals\", 
"logSeqJournalFolder": "d:\\Data\\Dropbox\\R&D\\R&D-2020\\KLTransitLogseq\\journals\\",
"logSeqJournalFolder": "../../KLTransitLogseq/journals/",
```

**Comment by scripting** [comment]
To @sabre23t @andrewshell @emk @logseqramses @tiensonqin @scotthansonde

Wanted to be sure everyone interested saw this. It would be helpful if we used this thread to deal with all problems that come up, that way we can all move forward together. Not sure what you have to do to get GH to send you an email when someone posts to this issue. Maybe just post a comment saying Hello World or something like that. :smile:

Anyway, here are my notes from yesterday's work -- a very eventful day. ;-)

http://oldschool.scripting.com/mylogseqblog/2022/01/14/000003.html?title=yesterdayMylogseqblogShipped

**Comment by scripting** [comment]
@sabre23t --

It looks like there is a JSON error in your config.json file. 

Basically none of your settings will get through to myLogseqBlog until we fix the JSON error. 

The software should not even attempt to do anything after such an error. I'm going to change it so it works that way. 

I'd be happy to help figure out what the problem is if you upload the config.json file somewhere. Or you can run the text through jsonlint.com and it'll show you.

**Comment by scripting** [comment]
@sabre23t -- from reading the code it could also be that config.json is not in the same folder as the myLogseqBlog app.

**Comment by logseqramses** [comment]
I'm getting all the messages, so it works!

**Comment by scotthansonde** [comment]
Having never used LogSeq before, I decided to give it a try to test myLogSeqBlog. Downloaded the latest release, started the app, then read the Getting Started to figure out what the hell I was supposed to do. 😄  Open a local folder, it said, so I hit the open button, created a folder, then got a journal page with today's date. I typed in some nonsense. I then installed myLogSeqBlog. Having used packages from @scripting before, the instructions were familiar. `npm install`, edit the config.json, run the script. And just like that, LogSeq has taken over my Drummer blog! Dec 30 was my last Drummer post, Jan 14 is from LogSeq. So it worked!

![image](https://user-images.githubusercontent.com/8681117/149563198-dcdeb198-a3d3-44ab-9df1-d2ef71a43ea6.png)

**Comment by sabre23t** [comment]
Dave wrote:
> It looks like there is a JSON error in your config.json file.

Yes you're right. I thought I replied your post last night. I may have just closed it without pressing "comment". Anyway, [your advise yesterday](http://oldschool.scripting.com/mylogseqblog/2022/01/14/000003.html?title=yesterdayMylogseqblogShipped) to use [jsonlint.com](https://jsonlint.com/) was really helpful for me to find the error with `\\` required instead of  `\` windows path separator and timezone cannot have "+" sign. 😄 

I've cleanup formatting of  [my yesterday's](http://oldschool.scripting.com/KLTransit/2022/01/14.html) "Logseq blogging on Drummer Day 1" post.

**Comment by sabre23t** [comment]
Today I did a bit more testing on *default* formatting of Logseq outline in Drummer Old School, [KLTransit Outline blog](http://oldschool.scripting.com/KLTransit/2022/01/15.html)
![KLTransit Outline blog 20220115 ss](https://user-images.githubusercontent.com/205024/149613474-89f683ba-30fb-48b6-ae37-1c34fa201d05.png)
I think it would be good if Old School CMS would process Drummer node type markdown in such manner that subs (and sub-subs) of headlines in a title post be indented similar to the source MD outline. This would be similar to processing of Drummer note type outline. I believe high proportion of Logseq users write in outline style, though there are some who do write in basic markdown document style.

I also found this error when writing my markdown outline blog today. 
```
d:>node mylogseqblog.js
config == {
    "twScreenName": "KLTransit",
    "logSeqJournalFolder": "d:\\Data\\Dropbox\\R&D\\R&D-2020\\KLTransitLogseq\\journals\\",
    "opmlJournalFile": " ",
    "blogTitle": "KLTransit Outline Blog",
    "blogDescription": "Journalling KLTransit from Logseq publishing to Drummer Old School",
    "blogWhenCreated": "Wed, 14 Jan 2022 00:20:00 GMT",
    "blogTimeZoneOffset": 8,
    "blogCopyright": "Copyright 2022, S M Sabri Ismail",
[...snipped...]
}
addJournalFileToOutline: fname == 2022_01_14-old.md, mdtext.length == 1341
addJournalFileToOutline: fname == 2022_01_14.md, mdtext.length == 2326
addJournalFileToOutline: fname == 2022_01_15.md, mdtext.length == 916
logseqpublish: opmltext.length == 7685
drummerCms: err.message == Can't read the file because there was an error. Code == 500.

d:>
```
Seems that journal file "2022_01_14-old.md" caused the error. When doing refactoring of journals pages I often make a copy using such name. Perhaps the journal file reader can filter out such file names?

**Comment by scripting** [comment]
That error usually means that the blog.opml outline isn't public.

Are you using the newest version of the myLogseqBlog software? v0.4.2

If not that's ok, you can either install it (just replace the .js file, being careful not to remove your config.json file. Or you can open blog.opml in Drummer and make it public. 

It looks like it processed 2022_01_14-old.md fine. 

About Markdown formatting, that was pretty tricky when we set it up originally, not something to change without a fair amount of consideration and thought.

**Comment by sabre23t** [comment]
Dave wrote:
> Are you using the newest version of the myLogseqBlog software? v0.4.2

I just updated to v0.4.2. I was on v0.4.1 in previous post.

I've tried to do a bit more with Markdown formatting as implemented in Logseq and Drummer in [KLTransit Outline Blog today](http://oldschool.scripting.com/KLTransit/2022/01/16.html). The bulleted list and unordered list looks much nearer what I usually want in my blog posts. Though, each markdown list item now looks like a paragraph on its own. I usually prefers to write lists as [a tight list not loose list](https://github.github.com/gfm/#loose). I don't think I can tweak that markdown within Logseq anymore. Screenshot below. Also ref [today's Logseq Markdown file](https://www.dropbox.com/s/s8d18km9dj0yxl2/2022_01_16.md?dl=0).
![KLTransit Outline blog 20220116 ss](https://user-images.githubusercontent.com/205024/149667314-8c3ea549-aa32-49e8-a127-cb5f818b6baa.png)

**Comment by scripting** [comment]
@sabre23t -- first of all -- I'm glad you're up and running. 

I've recorded a short voicemail on what I think should be the next step with this project.

http://scripting.com/2022/01/16/nextStepsOnMyLogseqBlogProject.m4a

It was much easier to do it this way than to write it all out.

The short version, myLogseqBlog functionality should be a plugin in LogSeq or added to Electric Drummer, or both, but I think the ideal place to put it is in LogSeq for a 100 percent integrated feel to it. 

I also think that's the best way to approach the Markdown mismatch issues you're writing about.

**Comment by sabre23t** [comment]
@scripting thanks for the voicemail. I answer to [sabre](https://www.youtube.com/watch?v=WvwnZ1LeBbY) or [sabri](https://www.youtube.com/watch?v=7Pro5wd-Mnc), usually. 😃 

I think myLogseqBlog.js v0.4.2 is already producing a workable [KLTransit Outline blog](http://oldschool.scripting.com/KLTransit/). Running `node mylogseqblog.js` in appropriate directory isn't too ornery for me. I was thinking of testing attributes llike "image" and "inlineImage" next for that Logseq-Drummer blog.

If myLogseqBlog functionality becomes a Logseq plugin or added to Electric Drummer for windows, I would certainly continue testing/using it. Even though I can mostly read mylogseqblog.js and its source.opml, I don't think I'm up to doing the Logseq plugin, yet.

**Comment by scripting** [comment]
@sabre23t -- thanks for the reply.

I tried testing the image attribute, it's supposed to work, but it didn't. I don't have time right now to investigate, but will soon.

I posted a [note on Scripting News](http://scripting.com/2022/01/17.html#a144334) looking for someone who can write a LogSeq plugin. I pointed to this thread and explained that you would work with them (so will I to the extent I can, I know very little about working in LS).

**Comment by scripting** [comment]
@sabre23t -- I have been chatting with a LogSeq plugin developer on Twitter DM.

We just added you to the thread. Also there is Ramses Oudt who is the community manager for LogSeq. 

I asked Ramses if he had any ideas and they recommended @hkgnp (that's a twitter handle) and we started discussing and I immediately realized you and he should be tlaking because:

1. You understand what the Node app is doing. 

2. You both understand LogSeq.

My problem is I don't know enough about LogSeq to be helpful. 

Amazingly he's in your timezone. A good omen I hope. ;-)

**Comment by scripting** [comment]
We're going to move the DM thread from Twitter to here, so we can get more minds focusing on the question.

The goal is to get the myLogseqBlog [Node app](https://github.com/scripting/myLogseqBlog/blob/main/mylogseqblog.js) ported to run as a LogSeq plugin. 

It should do exactly what the Node app does:

1. Gather up the last few days' journal outlines into an array of outlines.

2. The plugin code (ported from Node) will then turn that into OPML.

3. And then shoot it up to oldschool.scripting.com.

4. Somehow report success or failure to the user.

5. There must be a way for the user to set up the config options that are also transmitted in the OPML we send to the CMS server.

All of this functionality is implemented in JS in the Node app. It's basically, as I see it, a porting job.

**Comment by scottrblock** [comment]
hey @sabre23t, my port of @scripting's work is now available in the logseq plugin marketplace as "logseq opml drummer". it works very similarly to this, but with the addition of a parent tag to pull posts from. if this is something you're still interested in, i'd love any and all testing and feedback! feel free to open any issues or ping me directly!

you can find it in the logseq marketplace, but the source code is also directly available https://github.com/phonetonote/tft-interop/tree/main/logseq-opml-drummer

**Comment by sabre23t** [comment]
Hi @scottrblock . Thanks for working on this. I've updated my Logseq desktop app to v0.6.7. I've installed "logseq opml drummer" from Logseq Plugin Marketplace. I can now see "rocket icon" on top right of Logseq desktop app. But pressing it doesn't do anything it seems. Your [README.md](https://github.com/phonetonote/tft-interop/tree/main/logseq-opml-drummer) does refer to _"config to put into logseq package config"_ but I'm not too sure where that is supposed to be put into.

That's my testing for now. I'll reread this whole thread later, maybe that "config" issue will be clearer to me then. If we need interactive discussions I think [Logseq Discord plugins-general](https://discord.com/channels/725182569297215569/752845167030960141) channel may be a good place to do so.

Anyway, screenshots below ...
![logseq opml drummer installed 2022-05-07 092839](https://user-images.githubusercontent.com/205024/167233234-d90b10e8-58c6-4c99-976d-78c6130b28ef.jpg)
![logseq opml drummer journal rocket 2022-05-07 094615](https://user-images.githubusercontent.com/205024/167233240-c0aa69d6-246f-4712-a5fc-8e2b0e7e80fa.jpg)
